{% set name = "grpcio-gcp" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e292605effc7da39b7a8734c719afb12ec4b5362add3528d8afad3aa3aa9057c

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - grpcio >=1.16.0
    - protobuf >=3.6.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - google.protobuf
    - grpc
    - grpc_gcp
    - grpc_gcp.proto
    - grpc_gcp.proto.grpc_gcp_pb2

about:
  home: https://grpc.io
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: gRPC extensions for Google Cloud Platform
  description: |
    **gRPC-GCP Python**

    This repo is created to support GCP specific extensions for gRPC.
    To use the extension features, please refer to grpcio-gcp.

    This repo also contains supporting infrastructures such as
    end2end tests and benchmarks for accessing cloud APIs with gRPC client libraries.
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/GoogleCloudPlatform/grpc-gcp-python

extra:
  recipe-maintainers:
    - BrentDorsey
